# Generated by Django 4.1.1 on 2022-10-03 00:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=150)),
                ('salary', models.IntegerField(default=500)),
                ('location', models.CharField(default='', max_length=150)),
                ('image', models.ImageField(upload_to='', verbose_name='photos/%y/%m/%d')),
                ('created_at', models.DateField(default=datetime.datetime.now)),
                ('description', models.TextField(default='')),
                ('content', models.CharField(blank=True, max_length=75, null=True)),
                ('slug', models.CharField(blank=True, max_length=750, null=True)),
            ],
        ),
    ]
