# Generated by Django 4.1.1 on 2022-10-03 12:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0004_alter_job_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=250)),
                ('cv', models.FileField(upload_to='cv/%y/%m/%d')),
                ('your_skills', models.TextField(default='')),
                ('date_and_time', models.DateTimeField(default=datetime.datetime.now)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_apply', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
